#!/usr/bin/env bash

REPO_NAME="mobydock"

#number of pushed branches
n=0
#loop through args related to pushed branches
while read oldrev newrev refname
do
    n=$(($n+1))
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    count=0
    if [ "master" == "$branch" ]; then
        break
    fi
done

#build new image only if master was pushed or only one branch was pushed
if [ "master" != "$branch" -a count -gt 1 ]; then
    exit 0
fi

# Check out the newest version of the code.
export GIT_WORK_TREE="/var/git/${REPO_NAME}"
git checkout -f $branch

TAG="$(git log --pretty=format:'%h' -n 1)"
FULL_COMMIT_TAG="${REPO_NAME}:${TAG}"
FULL_LATEST_TAG="${REPO_NAME}:latest"

# Build the image with the proper commit tag.
docker build -t "${FULL_LATEST_TAG}" "${GIT_WORK_TREE}"

# Get the Docker ID of the last built image.
DOCKER_ID="$(docker images -q ${REPO_NAME} | head -1)"

# Tag a latest version based off a commit tag.
#docker tag -f "${DOCKER_ID}" "${FULL_LATEST_TAG}"

echo "Restarting ${REPO_NAME}"
docker stop "${REPO_NAME}"

echo "Removing untagged Docker images (may take a while)"
docker rmi $(docker images --quiet --filter "dangling=true")

docker stop "my-nginx"
